services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql-my-storage-management
    ports:
      - 6688:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - network
    environment:
      - MYSQL_ROOT_PASSWORD=password

networks:
  network:
    driver: bridge
    
volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: none
      device: D:\study_software\docker\MysqlData
      o: bind

#  docker-compose -p my-storage-management -f mysql.yaml up -d