services:

  storage-management-api:
    image: zeli8888/storage-management-api:${version}
    container_name: storage-management-api
    ports:
      - 8001:8000
    volumes:
      - ${FIREBASE_CREDENTIALS_FILE:-./secrets/firebase-private-key.json}:/home/storage-management-api/secrets/firebase-private-key.json:ro
    networks:
      - network
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - STORAGE_MANAGEMENT_POSTGRES_URL=jdbc:postgresql://storage-management-postgres:5432/storage-management

networks:
  network:
    driver: bridge